/**
 * LS Customs — Generated Supabase Database Types
 *
 * AUTO-GENERATED by `supabase gen types typescript --linked`.
 * Regenerate after every schema change: `npm run db:types` from the repo root.
 *
 * This is a placeholder. It will be replaced with real generated types
 * after Phase 1 (Schema & RLS) migrations are in place.
 */

// Placeholder export — replaced after first schema migration
export {};
