-- Migration: Update vehicles category to text and seed the most common Philippine vehicles
-- Supports the 7 categories: hybrid_ev, hatchbacks, sedans, minivans, suvs, van, pickup_trucks

-- 1. Alter category column to text
alter table public.vehicles alter column category type text;

-- 2. Clear any placeholder vehicles if needed
delete from public.vehicles where is_active is false and name like '%Test%';

-- 3. Seed 28 common Philippine vehicles
insert into public.vehicles (
  category,
  sub_category,
  name,
  description,
  seats,
  transmission,
  fuel_type,
  price_per_day,
  location,
  host_name,
  host_rating,
  features,
  rental_rules,
  mileage_policy,
  max_trip,
  delivery_methods,
  is_active,
  rating_avg,
  rating_count
) values
  -- =========================================================================
  -- 1. HYBRID EV
  -- =========================================================================
  (
    'hybrid_ev',
    'Compact Hybrid Crossover',
    'Toyota Corolla Cross 1.8 HEV',
    'The Philippines'' favorite compact hybrid crossover. Remarkable fuel economy (up to 23 km/L), Toyota Safety Sense, and smooth urban electric driving.',
    5,
    'Automatic',
    'Hybrid',
    3500.00,
    'Makati, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['Hybrid Electric Drive', 'Apple CarPlay & Android Auto', 'Toyota Safety Sense', 'Rear Parking Sensors', 'Automatic Climate Control'],
    array['Valid Driver''s License required', 'No smoking inside vehicle', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.95,
    28
  ),
  (
    'hybrid_ev',
    'Electric Crossover',
    'BYD Atto 3 EV',
    'Modern 100% electric crossover with 410km range on a single charge, panoramic sunroof, ultra-safe Blade Battery, and rotating 12.8-inch touchscreen.',
    5,
    'Automatic',
    'Electric',
    3800.00,
    'BGC, Taguig, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['Pure Electric 410km Range', 'Panoramic Sunroof', 'Rotating Infotainment Screen', 'Wireless Phone Charger', '360-Degree Camera'],
    array['Valid Driver''s License required', 'No smoking', 'Maintain minimum 20% battery upon return'],
    'Unlimited mileage within Luzon (EV charging network access)',
    '14 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.90,
    19
  ),
  (
    'hybrid_ev',
    'e-POWER Hybrid Crossover',
    'Nissan Kicks 1.2 e-POWER',
    '100% electric motor drive with an onboard 1.2L gasoline generator. Enjoy instant EV torque and one-pedal driving with zero range anxiety.',
    5,
    'Automatic',
    'Hybrid',
    3200.00,
    'Pasig, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['Instant Electric Torque', 'e-Pedal Step Driving', 'Nissan Intelligent Mobility', 'Keyless Push Start', '7-inch Digital Cluster'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.85,
    22
  ),
  (
    'hybrid_ev',
    'Subcompact Hybrid SUV',
    'Toyota Yaris Cross 1.5 S HEV',
    'Stylish and efficient hybrid crossover boasting exceptional ground clearance, dynamic styling, EV mode switch, and modern cockpit ergonomics.',
    5,
    'Automatic',
    'Hybrid',
    3300.00,
    'Quezon City, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['Full Hybrid Synergy Drive', 'Panoramic Sunroof', '10.1-inch Screen with Wireless CarPlay', 'Electronic Parking Brake', 'Blind Spot Monitor'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.92,
    15
  ),

  -- =========================================================================
  -- 2. HATCHBACKS
  -- =========================================================================
  (
    'hatchbacks',
    'Subcompact Hatchback',
    'Toyota Wigo 1.0 G',
    'The undisputed king of Philippine city driving. Exceptional fuel economy, agile maneuverability in heavy traffic, icy air conditioning, and easy parking.',
    5,
    'Automatic',
    'Gasoline',
    1400.00,
    'Manila, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['Superb 20+ km/L Fuel Economy', 'Apple CarPlay & Android Auto', 'Cold Dual Aircon', 'Keyless Push Start', 'Rear Sensors'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Metro Manila & nearby provinces',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.88,
    45
  ),
  (
    'hatchbacks',
    'Sporty Subcompact Hatchback',
    'Honda Brio 1.2 RS',
    'Sporty, punchy subcompact hatchback featuring Honda''s 1.2L i-VTEC engine, RS styling body kit, sharp handling, and premium interior accents.',
    5,
    'Automatic',
    'Gasoline',
    1600.00,
    'Mandaluyong, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['1.2L 4-Cylinder i-VTEC Engine', 'RS Aero Body Kit', '7-inch Touchscreen Audio', 'Sport Tuned Suspension', '15-inch Alloy Wheels'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.91,
    34
  ),
  (
    'hatchbacks',
    'Eco Hatchback',
    'Mitsubishi Mirage 1.2 GLX Hatchback',
    'Long-standing Philippine favorite renowned for legendary fuel efficiency, compact 4.6m turning radius, and reliable everyday urban commuting.',
    5,
    'Automatic',
    'Gasoline',
    1500.00,
    'Pasay, Metro Manila',
    'LS Customs Fleet',
    4.7,
    array['High Fuel Efficiency MIVEC Engine', 'Touchscreen Infotainment', 'Power Windows', 'Dual SRS Airbags', 'Compact Turning Radius'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Metro Manila & nearby provinces',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.79,
    39
  ),
  (
    'hatchbacks',
    'Compact City Hatchback',
    'Suzuki Swift 1.2 GL',
    'European-inspired sporty hatchback with responsive steering, lightweight chassis dynamics, modern cockpit layout, and striking floating-roof design.',
    5,
    'Automatic',
    'Gasoline',
    1700.00,
    'San Juan, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['Sporty Chassis Dynamics', '8-inch Infotainment Display', 'D-Shaped Steering Wheel', 'Dual Airbags & ABS', 'USB & Bluetooth Audio'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.84,
    18
  ),

  -- =========================================================================
  -- 3. SEDANS
  -- =========================================================================
  (
    'sedans',
    'Subcompact Sedan',
    'Toyota Vios 1.3 XLE',
    'The standard of Philippine roads. Renowned durability, generous rear legroom, icy dual-blower cooling, and dependable 1.3L Dual VVT-i performance.',
    5,
    'Automatic',
    'Gasoline',
    1800.00,
    'Makati, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['1.3L Dual VVT-i Reliability', '7-inch Display with Apple CarPlay', 'Coldest Air Conditioning in Class', 'Eco & Sport Drive Modes', 'Reverse Camera'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.93,
    58
  ),
  (
    'sedans',
    'Premium Subcompact Sedan',
    'Honda City 1.5 V',
    'Sophisticated executive styling with best-in-class 121hp 1.5L DOHC i-VTEC power, spacious cabin, premium sound system, and Honda SENSING safety suite.',
    5,
    'Automatic',
    'Gasoline',
    2200.00,
    'BGC, Taguig, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['121hp 1.5L DOHC i-VTEC', 'Honda SENSING Driver Assist', '8-inch Touchscreen CarPlay & Android Auto', 'Cruise Control', 'Push Button Engine Start'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.95,
    41
  ),
  (
    'sedans',
    'Compact Sedan',
    'Mitsubishi Mirage G4 1.2 GLS',
    'Practical, dependable 4-door sedan offering generous trunk volume (450 liters), comfortable passenger space, and remarkable fuel savings.',
    5,
    'Automatic',
    'Gasoline',
    1700.00,
    'Alabang, Muntinlupa, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['450L Massive Trunk Space', 'Keyless Operation System', 'Automatic Climate Control', '7-inch Smartphone-link Audio', 'Fog Lamps'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.82,
    30
  ),
  (
    'sedans',
    'Turbocharged Compact Sedan',
    'Nissan Almera 1.0 Turbo VE',
    'Advanced 1.0L Turbo engine delivering surprising highway passing power, comfortable Zero Gravity front seats, and Nissan Intelligent Around View Monitor.',
    5,
    'Automatic',
    'Gasoline',
    2000.00,
    'Pasig, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['1.0L Turbocharged Engine', 'Zero Gravity Comfort Seats', 'Around View 360-Degree Monitor', 'Forward Collision Warning', 'Apple CarPlay & Android Auto'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.87,
    25
  ),

  -- =========================================================================
  -- 4. MINIVANS
  -- =========================================================================
  (
    'minivans',
    '7-Seater Compact MPV',
    'Toyota Avanza 1.5 G',
    'The classic Philippine family transport. Flexible 7-seater seating with long-sofa folding mode, powerful dual air-conditioning, and high 190mm ground clearance.',
    7,
    'Automatic',
    'Gasoline',
    2500.00,
    'Quezon City, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['7-Passenger Seating with Sofa Mode', 'Front-Wheel Drive Fuel Efficiency', 'Rear Roof Air Conditioning Blowers', '8-inch Touchscreen Display', 'Blind Spot Detection'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.89,
    52
  ),
  (
    'minivans',
    '7-Seater Family MPV',
    'Mitsubishi Xpander 1.5 GLS',
    'The Philippines'' top-selling family MPV. Bold Dynamic Shield styling, class-leading 225mm ground clearance, and whisper-quiet 7-passenger cabin isolation.',
    7,
    'Automatic',
    'Gasoline',
    2800.00,
    'Makati, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['225mm High Ground Clearance', '7 Full Adult Seats', 'Rear Aircon Blowers with Speed Control', 'Electronic Parking Brake with Auto Hold', 'Smartphone Link Display Audio'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.94,
    64
  ),
  (
    'minivans',
    'Premium 7-Seater Crossover Minivan',
    'Toyota Veloz 1.5 V',
    'Upscale 7-seater MPV equipped with ambient interior lighting, wireless smartphone charger, 360-degree panoramic camera, and Toyota Safety Sense.',
    7,
    'Automatic',
    'Gasoline',
    3000.00,
    'BGC, Taguig, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['Panoramic 360-Degree Camera', 'Wireless Phone Charging Pad', 'Interior Ambient Lighting', 'Electronic Parking Brake', 'Full 7-Seater Comfort'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.96,
    37
  ),
  (
    'minivans',
    'Hybrid 7-Seater MPV',
    'Suzuki Ertiga Hybrid GLX',
    'Smart Hybrid 7-seater compact minivan that keeps fuel costs down on provincial road trips. Comfortable plush seats and easy luggage stowage.',
    7,
    'Automatic',
    'Hybrid',
    2600.00,
    'Paranaque, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['Smart Hybrid Engine Economy', '7-Seater Versatile Cabin', '10-inch Touchscreen Infotainment', 'Cruise Control', 'Keyless Push Start'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.86,
    29
  ),

  -- =========================================================================
  -- 5. SUVS
  -- =========================================================================
  (
    'suvs',
    'Midsize 7-Seater SUV',
    'Toyota Fortuner 2.4 G',
    'The undisputed king of Philippine roads. Rugged body-on-frame ladder chassis, bulletproof 2.4L D-4D turbo-diesel reliability, and commanding driving poise.',
    7,
    'Automatic',
    'Diesel',
    4200.00,
    'Makati, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['Heavy Duty Ladder Frame Chassis', '2.4L D-4D Turbo Diesel Power', '7 Full Seats with Tumble Fold', 'Dual Zone Climate Control', 'Power Folding Mirrors'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.96,
    72
  ),
  (
    'suvs',
    'Midsize 7-Seater SUV',
    'Mitsubishi Montero Sport 2.4 GLS',
    'Sophisticated midsize SUV powered by a 2.4L MIVEC Clean Diesel engine mated to an ultra-smooth 8-speed automatic transmission. Outstanding highway ride comfort.',
    7,
    'Automatic',
    'Diesel',
    4000.00,
    'BGC, Taguig, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['2.4L MIVEC Clean Diesel', '8-Speed Automatic Transmission', 'Plush Leather Trimmed Interior', 'Dual Zone Automatic Aircon', 'Paddle Shifters'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.93,
    55
  ),
  (
    'suvs',
    'Premium 7-Seater SUV',
    'Ford Everest 2.0 Turbo Titanium',
    'Muscular American engineering with panoramic dual-pane sunroof, massive 12-inch portrait touchscreen, 360-degree cameras, and effortless highway overtaking.',
    7,
    'Automatic',
    'Diesel',
    4500.00,
    'Mandaluyong, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['2.0L Bi-Turbo Diesel Engine', '12-inch Vertical Touchscreen Display', 'Dual-Pane Panoramic Sunroof', 'Hands-Free Power Liftgate', 'Wireless Apple CarPlay & Android Auto'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.97,
    48
  ),
  (
    'suvs',
    'Durable 7-Seater SUV',
    'Isuzu mu-X 3.0 LS-E',
    'Legendary Isuzu 3.0L Blue Power turbo-diesel reliability engineered for Philippine provincial roads, combined with advanced driver assist safety systems.',
    7,
    'Automatic',
    'Diesel',
    4000.00,
    'Alabang, Muntinlupa, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['3.0L Blue Power Turbo Diesel (190hp)', 'Advanced Driver Assist System (ADAS)', 'Power Tailgate with Step Sensor', 'Rough-Road Suspension Tuning', 'Full Leather Seating'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.88,
    33
  ),

  -- =========================================================================
  -- 6. VAN
  -- =========================================================================
  (
    'van',
    '15-Passenger Van',
    'Toyota HiAce Commuter Deluxe 2.8',
    'The standard of Philippine group travel and family out-of-town trips. Proven 2.8L 1GD-FTV diesel engine with robust dual rear air-conditioning and 15 seats.',
    15,
    'Manual',
    'Diesel',
    3800.00,
    'Pasay, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['15-Passenger High Capacity Seating', '2.8L 1GD-FTV Turbo Diesel', 'Powerful Overhead Dual Aircon Blowers', 'Anti-lock Braking System (ABS)', 'High Durability Suspension'],
    array['Valid Driver''s License required', 'No smoking inside vehicle', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.92,
    67
  ),
  (
    'van',
    '12-Passenger Executive Van',
    'Toyota HiAce Grandia 2.8 GL',
    'Top choice for executive trips, VIP airport transfers, and luxury family travel. Individual reclining captain-style seats with automatic transmission comfort.',
    12,
    'Automatic',
    'Diesel',
    5000.00,
    'Makati, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['12 Reclining Executive Seats', 'Automatic Transmission Comfort', 'Dual Zone High Output Air Conditioning', 'Touchscreen Audio System', 'Dual Sliding Side Doors'],
    array['Valid Driver''s License required', 'No smoking inside vehicle', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.97,
    59
  ),
  (
    'van',
    '15-Passenger Long Wheelbase Van',
    'Nissan NV350 Urvan Premium',
    'High-roof extended wheelbase van offering generous passenger headroom, wide center aisle, smooth highway stability, and dependable Nissan turbo-diesel torque.',
    15,
    'Manual',
    'Diesel',
    4200.00,
    'Quezon City, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['High-Roof Spacious Interior', '15 Full Passenger Seats', 'Individual Air Conditioning Vents', 'Rear Door Step Bar', 'Heavy-Duty Leaf Springs'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.86,
    38
  ),
  (
    'van',
    '11-Passenger Futuristic Luxury Van',
    'Hyundai Staria 2.2 CRDi',
    'Spacecraft-inspired futuristic exterior, expansive panoramic picture windows, whisper-quiet 2.2L turbo-diesel engine, and ultra-plush modern interior appointments.',
    11,
    'Automatic',
    'Diesel',
    5500.00,
    'BGC, Taguig, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['Futuristic Lounge Cabin', 'Panoramic Side Windows', '2.2L CRDi Clean Diesel (177hp)', '10.25-inch Digital Gauge Cluster', 'Smart Power Sliding Doors'],
    array['Valid Driver''s License required', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.98,
    31
  ),

  -- =========================================================================
  -- 7. PICK UP TRUCKS
  -- =========================================================================
  (
    'pickup_trucks',
    'Midsize Pickup Truck',
    'Toyota Hilux 2.4 Conquest',
    'The undisputed leader among Philippine pickups. Unbreakable durability, heavy cargo bed payload, bold Conquest styling, and robust 2.4L turbo-diesel power.',
    5,
    'Automatic',
    'Diesel',
    3500.00,
    'Pasig, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['Conquest Overfenders & Sports Bar', 'Heavy-Duty Bedliner', '2.4L D-4D Turbo Diesel Torque', 'Apple CarPlay & Android Auto', 'Hill-Start Assist Control'],
    array['Valid Driver''s License required', 'Cargo must be secured properly', 'No smoking inside cabin', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.95,
    63
  ),
  (
    'pickup_trucks',
    'Lifestyle Pickup Truck',
    'Ford Ranger 2.0 Turbo Wildtrak',
    'High-tech pickup truck with bold signature C-clamp LED headlights, integrated side bed steps, digital instrument display, and plush leather-stitched interior.',
    5,
    'Automatic',
    'Diesel',
    3800.00,
    'BGC, Taguig, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['Wildtrak Exterior Styling & Roof Rails', '12-inch SYNC 4A Touchscreen', 'Integrated Box Step for Easy Bed Access', 'Selectable Drive Modes', 'Wireless Phone Charger'],
    array['Valid Driver''s License required', 'Cargo must be secured properly', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.94,
    47
  ),
  (
    'pickup_trucks',
    'Heavy-Duty Work & Adventure Truck',
    'Isuzu D-MAX 3.0 LS-E',
    'Toughest diesel truck in the segment. Renowned for fuel economy, heavy-duty hauling capability, and reliable 3.0L Blue Power turbo-diesel engine.',
    5,
    'Automatic',
    'Diesel',
    3400.00,
    'San Juan, Metro Manila',
    'LS Customs Fleet',
    4.8,
    array['3.0L Blue Power Diesel (190hp / 450Nm)', '800mm Water Wading Depth', 'Heavy Payload Capacity', 'Rough Terrain Suspension', 'Dual Zone Climate Control'],
    array['Valid Driver''s License required', 'Cargo must be secured properly', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery'],
    true,
    4.89,
    36
  ),
  (
    'pickup_trucks',
    'Comfort Multi-Link Pickup Truck',
    'Nissan Navara 2.5 Calibre',
    'The smoothest riding pickup truck in the Philippines. Multi-link rear suspension with coil springs eliminates rear bounce, paired with comfortable Zero Gravity seats.',
    5,
    'Automatic',
    'Diesel',
    3600.00,
    'Makati, Metro Manila',
    'LS Customs Fleet',
    4.9,
    array['Multi-Link Rear Coil Spring Suspension', 'Zero Gravity Fatigue-Reducing Seats', 'Nissan Intelligent Around View Monitor', 'Rear Aircon Vents', 'Payload-Assist Tailgate'],
    array['Valid Driver''s License required', 'Cargo must be secured properly', 'No smoking', 'Return with same fuel level'],
    'Unlimited mileage within Luzon',
    '30 days max',
    array['Garage Pickup', 'Doorstep Delivery', 'Airport Drop-off'],
    true,
    4.91,
    42
  );
